### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by jas1t43** [austencm/youtube-auto-like#102]
![image](https://user-images.githubusercontent.com/26791273/161664360-6e8ddb9d-5eae-4d56-8369-42d0544ae228.png)

![1](https://user-images.githubusercontent.com/26791273/161664423-d0e2095c-63b9-4738-ac20-928f81c8bdb3.png)

__________________________
### Log
YouTube Auto Like v2.7.1
Tue Apr 05 2022
User agent: 
{
  "browser": {
    "name": "Chrome",
    "version": "99.0.4844.84"
  },
  "os": {
    "name": "Windows",
    "version": "NT 10.0",
    "versionName": "10"
  },
  "platform": {
    "type": "desktop"
  },
  "engine": {
    "name": "Blink"
  }
}
navigated: https://www.youtube.com/c/AnuragDwivedi/videos
loading options...
...options loaded ({
  "disabled": false,
  "like_what": "subscribed",
  "like_when": "instantly",
  "like_when_minutes": "2",
  "like_when_percent": "50"
})
liker started
waiting for buttons...

**Comment by austencm** [comment]
The service worker only runs briefly on launch to check for new releases, so it will be inactive most of the time. Guessing this was related to a YT layout change. Hopefully fixed in v2.7.2 or v2.7.3, but feel free to reopen if still not working!
