### ISSUE TITLE
not liking on %

### ISSUE THREAD

**Issue by theRTVance** [austencm/youtube-auto-like#105]
I am unsure if it is because I skipped forward. 
Works at 2 min setting.

__________________________
### Log
YouTube Auto Like v2.7.1
Sun Apr 24 2022
User agent: 
{
  "browser": {
    "name": "Chrome",
    "version": "100.0.4896.127"
  },
  "os": {
    "name": "Windows",
    "version": "NT 10.0",
    "versionName": "10"
  },
  "platform": {
    "type": "desktop"
  },
  "engine": {
    "name": "Blink"
  }
}
navigated: https://www.youtube.com/
loading options...
...options loaded ({
  "disabled": false,
  "like_what": "all",
  "like_when": "percent",
  "like_when_minutes": "2",
  "like_when_percent": "80"
})
liker started
waiting for video...

**Comment by austencm** [comment]
@theRTVance would you mind checking if this is still broken for you in v2.7.3?

**Comment by theRTVance** [comment]
I will need a week.
I am not going to be at a computer that has YouTube enabled for a few days.

**Comment by theRTVance** [comment]
Austen
It looks like it is working now.

Thank You!

--
R.T. Vance
