### ISSUE TITLE
Youtube Design Update - fix needed

### ISSUE THREAD

**Issue by StephanSteinert** [austencm/youtube-auto-like#106]
Liking not working anymore probably due a design change.

[Source Code Video Ct3IMbt958A.txt](https://github.com/austencm/youtube-auto-like/files/8691098/Source.Code.Video.Ct3IMbt958A.txt)

__________________________
### Log
YouTube Auto Like v2.7.1
Fri May 13 2022
User agent: 
{
  "browser": {
    "name": "Chrome",
    "version": "101.0.4951.54"
  },
  "os": {
    "name": "Windows",
    "version": "NT 10.0",
    "versionName": "10"
  },
  "platform": {
    "type": "desktop"
  },
  "engine": {
    "name": "Blink"
  }
}
navigated: https://www.youtube.com/
loading options...
...options loaded ({
  "disabled": false,
  "like_what": "all",
  "like_when": "percent",
  "like_when_minutes": "2",
  "like_when_percent": "50"
})

liker started
waiting for video..
.

**Comment by wthueb** [comment]
Looks like it's `yt-icon` instead of `yt-icon-button`. Not sure *why* YouTube would make that change, but alas.

**Comment by MCM-Math** [comment]
I'm wondering if austencm would still be working on this, and/or someone else could maintain their own update for this extension.

**Comment by StephanSteinert** [comment]
I changed the queryselector:

```
const r = document.querySelector("#menu #top-level-buttons-computed > ytd-toggle-button-renderer:first-child yt-icon-button"),
i = document.querySelector("#menu #top-level-buttons-computed > ytd-toggle-button-renderer:nth-child(2) yt-icon-button");
```
and it works for me so far. Meeds more testing and a proper merge request.
Replace the content.js with the attached file if yu trust me.
I also uncompressed the code so you can audit it.

[content.js.txt](https://github.com/austencm/youtube-auto-like/files/8710830/content.js.txt)

**Comment by austencm** [comment]
It's still working for me, which makes me think this is more A/B testing by youtube. But I'll go ahead and merge @wthueb's PR regardless.
