### ISSUE TITLE
It doesn't seem to work anymore.

### ISSUE THREAD

**Issue by Atype12** [austencm/youtube-auto-like#112]
Thanks to the development of a good program, I have been using it so far. However, the program hasn't worked anymore since about a week ago. The original setting was to operate after 50%of the video starts on all channels. Even now, if you set it immediately after playing, it may work very rarely, but in most situations, it no longer works.

__________________________
### Log
YouTube Auto Like v2.7.2
Sun Jul 03 2022
User agent: 
{
  "browser": {
    "name": "Chrome",
    "version": "103.0.0.0"
  },
  "os": {
    "name": "Windows",
    "version": "NT 10.0",
    "versionName": "10"
  },
  "platform": {
    "type": "desktop"
  },
  "engine": {
    "name": "Blink"
  }
}
navigated: https://www.youtube.com/watch?v=80Y4XPk3Sug
loading options...
...options loaded ({
  "disabled": false,
  "like_what": "all",
  "like_when": "instantly",
  "like_when_minutes": "2",
  "like_when_percent": "50"
})
liker started
waiting for buttons...

**Comment by MCM-Math** [comment]
Did you look at the extension settings?  Make sure it is set up to work with all videos, not just subscribed channels.  I don't know if that is what you are encountering, but it seems a good place to start.

**Comment by Atype12** [comment]
> Did you look at the extension settings? Make sure it is set up to work with all videos, not just subscribed channels. I don't know if that is what you are encountering, but it seems a good place to start.

Yes, the extension setting is already in 'all video'.
Originally, the setting I used to operate was '50% passed after starting playback' in 'All Video'.
Now, it does not work at all, but it works very rarely when set to 'immediately'.

**Comment by austencm** [comment]
Sorry for the wait! Please update to [v2.7.3](https://github.com/austencm/youtube-auto-like/releases/tag/v2.7.3) and let me know if you still have issues.

**Comment by CelsiusVi** [comment]
Hey, first of all, thank you for mantaining this extension and doing a great work.

However, I've tried updating to 2.7.3 after last week's YT update and it's not working for me at the moment. Neither option (all/sub videos, instant/time/%...) is doing anything for me, the extension just keeps saying "please refresh the page to see changes" but nothing does. I've restarted both chrome and my pc, disabled other extensions I thought could maybe interfere... but no chance.

Hopefully there's an easy change waiting to happen, otherwise just thanks for your time.

**Comment by austencm** [comment]
@CelsiusVi would you mind clicking the bug icon in the top right of the options page and paste the log that it generates here?

If you're comfortable using the dev console, could you also paste this in and let me know what it says? `window.ytcfg.get("INNERTUBE_CLIENT_VERSION")`

**Comment by CelsiusVi** [comment]
So apparently the log shows the extension is waiting for buttons, which aligns with what I thought by receiving the message, the new layout/interface makes it hard for it to recognise them.

And here's the Client version results

window.ytcfg.get("INNERTUBE_CLIENT_VERSION")
'2.20220921.08.00'
_________________________
### Log
YouTube Auto Like v2.7.3
Sat Sep 24 2022
User agent: 
{
  "browser": {
    "name": "Chrome",
    "version": "105.0.0.0"
  },
  "os": {
    "name": "Windows",
    "version": "NT 10.0",
    "versionName": "10"
  },
  "platform": {
    "type": "desktop"
  },
  "engine": {
    "name": "Blink"
  }
}
navigated: https://www.youtube.com/watch?v=W4KIWfeFkYI
loading options...
...options loaded ({
  "disabled": false,
  "like_what": "all",
  "like_when": "instantly",
  "like_when_minutes": "2",
  "like_when_percent": "5"
})
liker started
waiting for buttons...

**Comment by austencm** [comment]
Strange, on my PC I get that client version too and no issues. I'm still on windows 10 but I don't think that matters here.

Ok, one more thing to try: can you go to a video page, Ctrl-S, and attach the file here?

**Comment by CelsiusVi** [comment]
Sure thing, I was just watching one, so this is it.
I disabled every other extension just to make sure and it still fails the same. I don't really know why either, hope this helps us out.
[youtube.zip](https://github.com/austencm/youtube-auto-like/files/9639856/youtube.zip)

**Comment by austencm** [comment]
Ok that is very interesting. YouTube tests a number of "experiments" on different people and you're getting a lot that I don't have. Your buttons are super different. I'll work on a patch.

Thinking about this, it would be useful to try to keep a list of known experiments and include unknown ones in bug reports. Would be nice to have button markup in there too. I'll put it in planned features.

**Comment by CelsiusVi** [comment]
Huh, that's interesting. I was really confused, seeing that many people were successful with this extension, the monkey script and other methods, while I was having trouble for the first time in forever. Sorry I can't be of much help with the code side, not my strong suit, but I hope it can be solved as you say :D

**Comment by austencm** [comment]
Try https://github.com/austencm/youtube-auto-like/releases/tag/v2.7.4 when you get a chance!

**Comment by CelsiusVi** [comment]
Fabulous, you did it!
It works great now, thanks for taking the time to implement the changes. Many channels will appreciate having all of their likes again instead of those where I remember to haha
