### ISSUE TITLE
google removes extension 

### ISSUE THREAD

**Issue by Drifter128175** [austencm/youtube-auto-like#116]
google removes this extension every single day once a day and then i reinstall it everyday once a day. its a pain but i like the extension. this been going on for some weeks now, any ideas?

**Comment by austencm** [comment]
Weird, I haven't seen this happen. Where are you keeping the folder with the extension?

**Comment by Drifter128175** [comment]
hidden folder D drive.  i also been keeping a zipped copy on my desktop for a quick reinstall.

**Comment by austencm** [comment]
Sorry about the wait! Only speculating here, but maybe the hidden folder is causing issues? I'd try it somewhere else if you haven't already. What's your OS and browser?

**Comment by Drifter128175** [comment]
its fine now. i used google chrome just for watching YouTube only. i ditched chrome for Firefox for watching YouTube and problem salved. i been itching to pull that trigger anyway.
