### ISSUE TITLE
Extension Quit Working 9-13-22

### ISSUE THREAD

**Issue by BG1959** [austencm/youtube-auto-like#117]
The extension has been updated.
I tried removing and reinstalling it.
I tried selecting different activation times and "which videos" options.
Nothing seems to help, it still does not work.

Thanks,
BG

**Comment by austencm** [comment]
Should be fixed in [v2.7.3](https://github.com/austencm/youtube-auto-like/releases/tag/v2.7.3), but feel free to reopen if you still have issues.

**Comment by BG1959** [comment]
Works!Thanks, Austen!
    On Thursday, September 22, 2022 at 06:57:31 PM CDT, Austen Morgan ***@***.***> wrote:  
 
 


Closed #117 as completed.
