### ISSUE TITLE
Quit working again

### ISSUE THREAD

**Issue by BG1959** [austencm/youtube-auto-like#118]
I recently updated it and it worked just fine for a few days, then today it has quit working.

Thank You,
BG

__________________________
### Log
YouTube Auto Like v2.7.3
Wed Sep 28 2022
User agent: 
{
  "browser": {
    "name": "Chrome",
    "version": "105.0.0.0"
  },
  "os": {
    "name": "Windows",
    "version": "NT 10.0",
    "versionName": "10"
  },
  "platform": {
    "type": "desktop"
  },
  "engine": {
    "name": "Blink"
  }
}
navigated: https://www.youtube.com/watch?v=s16jt82H7BA
loading options...
...options loaded ({
  "disabled": false,
  "like_what": "all",
  "like_when": "timed",
  "like_when_minutes": "2",
  "like_when_percent": "50"
})
liker started
waiting for video...

**Comment by austencm** [comment]
Dang! Can you go to a video, Ctrl-S, and attach the file here?

**Comment by BG1959** [comment]
Austen, it started working again all on its own.Not sure what it was, but it's working now.Thank you!
P.S. When I can I will donate to you for this app. Thanks!
    On Wednesday, September 28, 2022 at 04:13:11 PM CDT, Austen Morgan ***@***.***> wrote:  
 
 


Dang! Can you go to a video, Ctrl-S, and attach the file here?
