### ISSUE TITLE
Doesn't work on Chromebooks / ChromeOS?

### ISSUE THREAD

**Issue by austencm** [austencm/youtube-auto-like#12]
I've been told the extension just straight up does not function, but I have no way of testing it. If anyone with a Chromebook would like to take a crack at it, please do.

**Comment by seanthaswan** [comment]
Hey @austencm - I've just recently stumbled upon your extension and have been able to test it on my Chromebook. It worked flawlessly on my Lenovo C330 running Chrome 85.0.4183.133.

I was curious to see what the issue was but it turns out I can't find one!
