### ISSUE TITLE
YouTube Autoliker not detecting subscribed state?

### ISSUE THREAD

**Issue by HighMans** [austencm/youtube-auto-like#123]
It seems to work if I set it to like all videos, but when set to like only subscribed videos it doesn't work.
[Attached Saved Website](https://github.com/austencm/youtube-auto-like/files/9719752/Yakuza.Kiwami.-.Part.4.-.YouTube.zip)

__________________________
### Log
YouTube Auto Like v2.7.4
Wed Oct 05 2022
User agent: 
{
  "browser": {
    "name": "Chrome",
    "version": "105.0.0.0"
  },
  "os": {
    "name": "Windows",
    "version": "NT 10.0",
    "versionName": "10"
  },
  "platform": {
    "type": "desktop"
  },
  "engine": {
    "name": "Blink"
  }
}
navigated: https://www.youtube.com/watch?v=S4B3ete1gkY
loading [options...](url)
...options loaded ({
  "disabled": false,
  "like_what": "subscribed",
  "like_when": "instantly",
  "like_when_minutes": "2",
  "like_when_percent": "50"
})
liker started
waiting for buttons...
liker started
waiting for buttons...
...buttons ready
user not subscribed
paused
...buttons ready
user not subscribed
paused

**Comment by frozenparagon** [comment]
i'm getting this issue intermittently. It did this the firstime i loaded it, but a reload of chrome sorted it. the second time i installed the extension there was no issue, this is the third time and the extension folder is loacated on my root and it won't detect subscribed state. i'm going to try moving the folder around and readding the extension

**Comment by frozenparagon** [comment]
So i moved the folder to my user profiles' documents (windows) which doesn' thave the permissions that root does and readded the extension. at first it didn't do subscribe, but i toggled it to all, refreshed, that worked, then toggled back over to subscribe, refreshed and... still not working :(

I have the latest win10 update and am using latest chrome

**Comment by JackDjTom** [comment]
I have the issue that videos from channels I subscribed, won't get liked. But videos from unsubscribed channels will get liked...

**Comment by austencm** [comment]
Should be fixed in https://github.com/austencm/youtube-auto-like/releases/tag/v2.7.5. Let me know if it's still broken for you.
