### ISSUE TITLE
Since yesterday when they changed the layout it doesn't work anymore :(

### ISSUE THREAD

**Issue by riccardosimo** [austencm/youtube-auto-like#125]
Since yesterday when they changed the layout it doesn't work anymore :(

__________________________
### Log
[no log found]

**Comment by austencm** [comment]
Hey @riccardosimo, can you confirm you're using the latest version?

If you are, could you go to a video, save the page, and attach it here? (right click -> save as)

**Comment by riccardosimo** [comment]
> Hey @riccardosimo, can you confirm you're using the latest version?
> 
> If you are, could you go to a video, save the page, and attach it here? (right click -> save as)

Fixed it after few days :)
