### ISSUE TITLE
[Bug] update issue

### ISSUE THREAD

**Issue by JackPlaysGames0510** [austencm/youtube-auto-like#136]
it still tell me to up the plugin even thou i just have updated it

**Comment by austencm** [comment]
Try restarting your browser? I'm not sure if it's because I added an extra dot to the v2.8.0 tag name or an issue with the update checker. Will look into it.

**Comment by austencm** [comment]
Just to make sure, is the version 2.8.0 on your extensions page?

**Comment by JackPlaysGames0510** [comment]
yes it is

**Comment by austencm** [comment]
Reinstalling might fix it. Are you using Chrome?

**Comment by JackPlaysGames0510** [comment]
yes i am

**Comment by JackPlaysGames0510** [comment]
it seems to be fine
