### ISSUE TITLE
Doesn't work with youtube leanback (youtube.com/tv)

### ISSUE THREAD

**Issue by JacobGates** [austencm/youtube-auto-like#15]
I have a a computer hooked up to a TV and I use youtube leanback/tv for it and it's a lot of button presses to like a video so that is why I installed this, however it doesn't seem to work with it. Probably because the interface is pretty different. Not sure if it's possible to add the ability to the extension but if it is I would really like it.

**Comment by austencm** [comment]
Closing this since leanback is shutting down.
