### ISSUE TITLE
No autolike

### ISSUE THREAD

**Issue by MoweME** [austencm/youtube-auto-like#20]
> Thanks for reporting! Please fill in the following info:

OS (Windows / MacOS / etc.): Windows 10 (Chrome Version 69.0.3497.10)

YouTube version (YouTube / YouTube Gaming): YouTube

What happened: Nothing. The addon does not like the videos.

What should have happened: The addon is supposed to like the videos of subscriptions half the time.

Anything helpful to reproduce the issue: No. Sorry.

Current settings (leave this alone):
disabled: false, like_what: subscribed, like_when: percent

**Comment by austencm** [comment]
Is this still happening? 2.3.2 fixed a couple issues that may have been causing this.

**Comment by MoweME** [comment]
It's working now. Thanks for your help!
