### ISSUE TITLE
 Latest YouTube posts bug

### ISSUE THREAD

**Issue by mateusPreste** [austencm/youtube-auto-like#23]
> Thanks for reporting! Please fill in the following info:

OS (Windows / MacOS / etc.): Windows 10 

YouTube version (YouTube / YouTube Gaming): Youtube

What happened: this extension like Latest YouTube posts section

What should have happened: nothing

Anything helpful to reproduce the issue: no

Current settings (leave this alone):
disabled: false, like_what: subscribed, like_when: percent

**Comment by Taknok** [comment]
Hi,

Are you speaking of this URL https://www.youtube.com/user/[NAME]/community ? If not, could you provide the URL or a screenshot of the mentionned section ?
