### ISSUE TITLE
Not Autoliking

### ISSUE THREAD

**Issue by N8teZero** [austencm/youtube-auto-like#24]
> Thanks for reporting! Please fill in the following info:

OS (Windows / MacOS / etc.): Windows 10

YouTube version (YouTube / YouTube Gaming): Youtube

What happened: Not autoliking subscribed videos anymore

What should have happened: Should have autoliked

Anything helpful to reproduce the issue: Subscribed to channel for long time, play video, doesn't autolike instatly.

Current settings (leave this alone):
disabled: false, like_what: subscribed, like_when: instantly

**Comment by StephanSteinert** [comment]
Still not working...
Is there an alternative extension out there?

**Comment by Taknok** [comment]
Hi,
I'm the firefox developer, I will take a look tomorrow to this chrome version. Could you tell me if you use any other addon that may interfer ?

**Comment by StephanSteinert** [comment]
Tried with disabling some addons and now it works completly, even with 2min. delay. Maybe just a restart of Chrome or page reload was needed.

If i remove a like and reload the page with the same video it doesn't get reliked but that's probably an unusual scenario.

Sorry for wasting your time.

**Comment by Taknok** [comment]
OK, no problem. Quite strange the reload issue, the script should be injected at reload and the video should be liked...

**Comment by StephanSteinert** [comment]
It's a playlist, maybe it's a difference?

**Comment by Taknok** [comment]
If you only click in the playlist iframe, it's a normal behavior : the page is not reloaded only the video element. If you reload the page with the reload button on the navigator it's not normal

**Comment by austencm** [comment]
@StephanSteinert I fixed a bug in 2.4.0 that might have fixed your original issue. Maybe it wasn't getting updated until now for some reason.

I'll look into potential issues with playlists — it isn't a use case I've tested much.

**Comment by StephanSteinert** [comment]
Thank you.

Is there no release of it, is it?

**Comment by austencm** [comment]
2.4.0 has been released for a while. I was wondering if somehow it wasn’t updated on your end until you restarted chrome...but that seems unlikely.

More likely the issue is an edge case I have yet to pin down. There are several ways to navigate between videos on YouTube which makes testing & debugging _a process_.

**Comment by StephanSteinert** [comment]
Ah ok i thought there will be a new version.
I suspect https://chrome.google.com/webstore/detail/myjdownloader-browser-ext/fbcohnmimjicjdomonkcbcpbpnhggkip as a conflict as the liker didn't work until i disabled this addon.

**Comment by austencm** [comment]
Good to know. I’ll check it out.

**Comment by austencm** [comment]
I don't see anything in myjdownloader that would conflict with this extension. It's a big one though so I may have missed something.

@StephanSteinert/@N8teZero are you still experiencing issues?
