### ISSUE TITLE
Updated translations for web store description, etc.

### ISSUE THREAD

**Issue by austencm** [austencm/youtube-auto-like#27]
Hello lovely translators. I updated the web store description to make it more clear and concise (and less...slangy?). If anyone wants to take a crack at updated translations, that would be awesome. 👍 

The following keys were either updated or were features added after the translation was done. If it's easier, put translations directly in the comments and I can add them.

#### "appStoreDesc":
> Presses the like button so you don't have to!
>
> Features:
> - Like videos instantly from subscribed channels, or like every video
> - Be more selective: like after you've watched 2 minutes or 50% through
> - Waits for ads to finish when using a timed option
> - Won't override your choice if you've already disliked a video
> - Lightweight: won't slow down your YouTube load time
>
> Feed my cats:

#### "optLikePercent":
> After watching 50%

#### "linkReport":
> Report a bug

**Comment by UtkuGARIP** [comment]
Turkish

"appStoreDesc":
İzlediğiniz videolarda otomatik olarak "Beğen" butonuna basar!

Features:

Sadece abone olduğunuz kanalın videosunu veya abonesi olmadığınız kanalın videosunu beğenebilme seçeneleri
Ne zaman?: Örneğin 2 dakika veya %50'sini izledikten sonra beğenebilme
Zamanlanmış bir seçenek kullanıldığında reklamların bitmesini bekler
Zaten bir videoyu beğenmediyseniz, beğeniyi geri almaz
Hafif: YouTube yükleme sürenizi yavaşlatmaz
Kedilerimi besle:

"optLikePercent":
%50'sini izledikten sonra

"linkReport":
Hata bildir
