### ISSUE TITLE
Youtube doesn't work anymore.. Layout changed

### ISSUE THREAD

**Issue by jadslim313** [austencm/youtube-auto-like#3]
Hey, I love your extension and use it almost all the time. unfortunately, they changed their layout and it doesn't work anymore. Will you be able to fix it anytime soon? Thanks

**Comment by austencm** [comment]
Hey, thanks for the heads up! I've been swamped but I'll update it ASAP.

**Comment by Victor4X** [comment]
Also, doesn't work with the "new Youtube" on https://www.youtube.com/testtube. It isn't implemented yet afaik, but I thought I'd let you know anyway =) Love your extension btw

**Comment by Victor4X** [comment]
Just realized that this might be what jadslim was talking about. Sorry to bother you.

**Comment by austencm** [comment]
@Victor4X Are you specifically talking about https://www.youtube.com/new? The latest update was supposed to fix issues with the new design :(

Is it working inconsistently, or just not working at all?

**Comment by Victor4X** [comment]
It seems I was mistaken. I was probably just somewhat blind. It's working perfectly.

**Comment by austencm** [comment]
Glad you like it!
You might not be going insane...I might have seen it not work once too. Further investigation needed.
