### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Cavagies** [austencm/youtube-auto-like#31]
> Thanks for reporting! Please fill in the following info:

OS (Windows / MacOS / etc.): Windows 10

YouTube version (YouTube / YouTube Gaming): Youtube

What happened: The extension is not working.

Anything helpful to reproduce the issue:

Current settings (leave this alone):
disabled: false, like_what: all, like_when: instantly

**Comment by igormanancial** [comment]
no auto like
