### ISSUE TITLE
Autolike deactivating autoplay of the playlist

### ISSUE THREAD

**Issue by Intersekt00** [austencm/youtube-auto-like#32]
OS (Windows / MacOS / etc.): Windows 10

YouTube version (YouTube / YouTube Gaming): Youtube

What happened: while playing my "watch later" video playlist, if I activate the AUTOPLAY function (double squared arrows button) the next video starts at the end of the current one (as it should be) but the AUTOPLAY function is turned off as soon as youtubeautolike adds the like to the video.

Anything helpful to reproduce the issue:

Current settings: 
disable: false, like_what: only_subbed, like_when: instantly

**Comment by austencm** [comment]
Is this still an issue? It seems like youtube removed the autoplay toggle in playlists. Or maybe I'm just blind.
