### ISSUE TITLE
Like Delays Not working

### ISSUE THREAD

**Issue by BG1959** [austencm/youtube-auto-like#33]
> Thanks for reporting! Please fill in the following info:

OS (Windows / MacOS / etc.): Windows 10

YouTube version (YouTube / YouTube Gaming): YouTube

What happened: It will only "Like" instantly, neither of the delays works.

Anything helpful to reproduce the issue: It is constantly that way, no need to "reproduce."

Thank you,
BG

Current settings (leave this alone):
disabled: false, like_what: all, like_when: timed

**Comment by Snak3Doc** [comment]
Yea I'm getting this issue as well

**Comment by austencm** [comment]
Looking into this, thanks guys.

**Comment by Snak3Doc** [comment]
If it helps I think it may have happened after Vivaldi updated to the latest version of chromium, but not 100% sure, it was definitely working around 3 weeks ago on Vivaldi browser, not sure a GChrome.

**Comment by Snak3Doc** [comment]
Seems to have fixed its self, not sure if it was because I swapped from >50% to instantly and back to >50% or if something changed in chromium.

**Comment by austencm** [comment]
Interesting...thanks for the update.

**Comment by austencm** [comment]
Closing this, but please let me know if it happens again.
