### ISSUE TITLE
Extension does not function after adding videos to Watch Later playlist

### ISSUE THREAD

**Issue by CharlesMagnuson** [austencm/youtube-auto-like#36]
**Issue description**: 
If I go straight to my Watch Later playlist and begin playing videos, this extension will function correctly by liking the videos I watch. However, if I go to My Subscriptions, add some videos to my Watch Later playlist, and then begin watching videos from that playlist, this extension will not function correctly as it will no longer like videos.

To fix this problem, I have to close the current tab, open a new tab, navigate back to my Watch Later playlist, and begin watching videos again. Only then will the extension begin to like videos again.

**Steps to reproduce**:
1. Open YouTube.com and navigate to your My Subscriptions page.
2. Hover your mouse over the thumbnails of videos you want to add to your Watch Later playlist and click on the + button that appears on hover.
3. After adding some videos to your Watch Later playlist, navigate to your Watch Later playlist using the link in the left sidebar.
4. Click on one of the videos in your Watch Later playlist to begin watching videos from the playlist.
5. Note how the extension is no longer functioning correctly as it will no longer like any videos.
6. Close that tab you are viewing, open a new tab, and navigate back to your Watch Later playlist.
7. Click on any video in the playlist to begin watching videos from the playlist. Note how the extension is now functioning correctly again.

**Screencast illustrating issue**:
I have recorded a short screencast where I reproduce this issue. I apologize that you have to watch the YouTube video twice for several moments as I wait for the playhead to reach 50% since I've configured this extension to only like videos upon reaching the 50% mark: http://ca.mag.cm/502ef93ea821

**Desired resolution**:
This extension should like the YouTube videos I watch after I add videos to my Watch Later playlist. I should not have to open a new tab to begin watching videos.

**Other information**:
OS: Windows 10
Browser: Chome v77.0.3865.90
YouTube version: the "new" YouTube UI
Current settings: disabled: false, like_what: all, like_when: percent

**Comment by Taknok** [comment]
Hi,
What is your youtube version ? Is that the ["old" youtube](https://i.ytimg.com/vi/e4b740i-O4E/maxresdefault.jpg) or the ["new" youtube](https://cdn3.vox-cdn.com/thumbor/-Y2YkLmBPumr-5AZZG-XvDDH8fE=/640x0/filters:no_upscale()/cdn0.vox-cdn.com/uploads/chorus_asset/file/8449641/Home_before.png)
Thank you for reporting the bug and providing clean steps to reproduce the issue !

**Comment by CharlesMagnuson** [comment]
@Taknok Sorry for failing to distinguish! I had no idea people could still access the "old" YouTube. Based on your images, I believe I am using the "new" YouTube.

**Comment by Taknok** [comment]
In your record I can see others extensions, could you list them ? They may interfer with auto like. I couldn't reproduce the issue on a vanilla chrome. I also tested in large screen mode and with bringbackbird video like in your record without success (the like worked).

**Comment by CharlesMagnuson** [comment]
Here is a list of the Chrome extensions I use:
- 1Password
- Add to Deliveries
- Application Launcher for Drive (by Google)
- AutoScroll
- BehindTheOverlay
- Bird Eats Bug
- Block Website Notification Requests
- Cato
- Clear Downloads
- Dark Reader
- Decentraleyes
- Disable links
- Don't add custom search engines
- Enhanced Image Viewer
- FasterChrome
- FastMail Enhancement Suite
- Follow the Money
- Freezetab
- Full Page Screen Capture
- Go Back With Backspace
- Go Links
- Google Docs Offline
- Google Translate
- InstaG Downloader
- Mailto:
- Minimal Scrollbar
- Mute Tab
- Old Reddit Redirect
- Open in IINA
- Pay by Privacy.com
- Picture-in-Picture Extension (by Google)
- Print Friendly & PDF
- Reddit Enhancement Suite
- Save to Pocket
- Scrollbar Anywhere
- Scrroll In
- Search Youtube Right Click
- Smile Always
- Smooth Gestures Plus
- Snap Scroll
- Spoiler Protection 2.0
- Super Auto Refresh Plus
- Tab to Window/Popup - Keyboard Shortcut
- Tampermonkey
- The Great Suspender
- uBlock Origin
- Unsplash Instant
- View Image
- Watch Later
- Wikipedia IPA Speaker
- YouTube Auto Like


However, to test your theory that another one of these extensions is causing trouble, I performed the following test:
1. I disabled every extension except for YouTube Auto Like. 
2. I quit Chrome so that the application was no longer running.
3. I relaunched Chrome, navigated to my YouTube subscriptions, added a couple videos to my Watch Later playlist, navigated to the playlist, and began watching a video. The video was not auto-liked when I reached the 50% playback mark.

I have recorded another screencast which begins just after I relaunch Chrome (step 3 above) where I demonstrate that YouTube Auto Like is the only extension enabled, yet it still doesn't auto-like the video I'm watching: http://ca.mag.cm/287c7424be4c

Let me know if you would like me to perform further testing.

**Comment by Taknok** [comment]
Thank you for all the returns and the video ! It helps a lot for debugging ! Just noticing ! You have youtube premium, isn't it ?

**Comment by Taknok** [comment]
If you have youtube premium, could you test with a non premium account ? With your premium account on firefox and [the addon](https://addons.mozilla.org/fr/firefox/addon/youtube_auto_like/). I am sorry to ask you that much tests :/
