### ISSUE TITLE
Missing FR traduction

### ISSUE THREAD

**Issue by Starmania** [austencm/youtube-auto-like#45]
Hey, the :fr: traduction for "After watching 50%" is just in English, and the traduction "A quelle vitesse" is bad, it's "A quel moment?"
A screen to help you : 
![screen](https://user-images.githubusercontent.com/52313983/83608781-a1aa2980-a57d-11ea-8a4d-274814dbcda6.png)
The end text is : "Des heures de développement et de test sont nécessaires pour maintenir cette extension. Si vous pensez que cela vaut quelques euros, vous pouvez aider à nourrir mes chatons ici. J'apprécie vraiment. <3"

**Comment by austencm** [comment]
Added in [v2.7.3](https://github.com/austencm/youtube-auto-like/releases/tag/v2.7.3)
