### ISSUE TITLE
Why can i no longer select how long before liking a video? i can choose only set a preset time now

### ISSUE THREAD

**Issue by NancokPS2** [austencm/youtube-auto-like#47]
__________________________
### Log
Thu Jun 25 2020
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
YouTube variant: material
navigated: https://www.youtube.com/watch?v=RiiIxBqDC_Y
loading options...
...options loaded (disabled: false,like_what: subscribed,like_when: instantly)
liker initialized
waiting for buttons...
liker initialized
waiting for buttons...
...buttons ready
like button clicked
stopped
...buttons ready
video already rated
stopped

**Comment by austencm** [comment]
This was never a feature, although I'd like to add it at some point. Maybe you're thinking of the Firefox version?

**Comment by NancokPS2** [comment]
Oh, maybe, yeah, nvm then
Jun 26, 2020, 24:29 by notifications@github.com:
