### ISSUE TITLE
auto-like

### ISSUE THREAD

**Issue by amirasrhaf** [austencm/youtube-auto-like#53]
__________________________
### Log
Thu Aug 27 2020
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
YouTube variant: material
navigated: https://www.youtube.com/channel/UCuB9KlEe1ImdWaiBv41yzKA?view_as=subscriber
loading options...
...options loaded (disabled: false,like_what: subscribed,like_when: percent)
liker initialized
not a watch page
stopped
liker initialized
not a watch page
stopped

**Comment by markygnlg** [comment]
4 things you might want to test/try:
'
- there is now a v2.7.1 which was released about 24hrs ago as of this writing:
https://github.com/austencm/youtube-auto-like/releases
'
- secondly, I too found it 'not working' (with the 50% setting) but if I pressed 'F5'/refresh or opened the video in another tab (same as refreshing the page) the like button would be lit up: ie. it works but the graphics of the thumb only displays if you press refresh (I'm using v2.7.1 on Opera)
'
- try testing with 'Instantly'
'
- updates default to "Only videos from subbed channels" - it's working for me on all videos after I changed the setting to "ALL videos"
'
P.S.
 Sadly, Chrome removed this extension for violating YouTube's terms of service (specifically the part about causing inaccurate measurements of user engagement). [from https://github.com/austencm/youtube-auto-like ... or click on the like "CODE" at the top of the page]

**Comment by austencm** [comment]
Hey @amirasrhaf, it looks like you're using an older version of the extension. If you're using the version from the web store, read here: https://github.com/austencm/youtube-auto-like#youtube-auto-like. If you already followed those steps, then please try the [latest release](https://github.com/austencm/youtube-auto-like/releases/download/v2.7.1/release.zip).
