### ISSUE TITLE
Automatically like after amount of time watched

### ISSUE THREAD

**Issue by JKetelaar** [austencm/youtube-auto-like#6]
Currently it likes every video, no matter how long you watch it (if you enable the like all option), but I'd like to see an option where it would only like it after 50% is watched of the video.
This indicates that I've seen enough to be sure to like the video and that it wasn't some sort of clickbait or accidental click from myself.

**Comment by austencm** [comment]
This is definitely on the to-do list. I feel like engagement with a video would be better measured as a fixed amount of time watched. What do you think about a 1 or 2 minute countdown instead of a percentage? (And for videos shorter than that, at the end of the video?)

**Comment by Taknok** [comment]
Hi !

I implemented this functionality in my repo if you want. I have a different file structure and I'm a bit lazy to change it to push a PR :/
If you want a contributor added the german too.

Lazy guy out !

**Comment by austencm** [comment]
Nice, @Taknok! No worries, I'll grab your repo at some point and take a look.

**Comment by austencm** [comment]
This will be in v2.02, coming today or tomorrow!
