### ISSUE TITLE
FYI: It got disabled today automatically in my Chrome, because "it contains malware".

### ISSUE THREAD

**Issue by kurtextrem** [austencm/youtube-auto-like#60]

**Comment by Combie81** [comment]
Can confirm that I also noticed the same, hopefully this can be resolved

**Comment by MoweME** [comment]
It looks like it's not a false positive.
Some users have been reporting for days about affiliate links suddenly appearing when they go directly to the pages of large stores.

However, I do not guarantee that it is so.

**Comment by austencm** [comment]
Thanks for the heads up guys, closing this in favor of #61. See my comment there for more info.
