### ISSUE TITLE
New like buttons on YouTube

### ISSUE THREAD

**Issue by wthueb** [austencm/youtube-auto-like#66]
I believe the like button changed due to YouTube having an update.

__________________________
### Log
Mon Mar 22 2021
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
YouTube variant: material
navigated: https://www.youtube.com/feed/subscriptions
loading options...
...options loaded (disabled: false,like_what: all,like_when: percent)
liker initialized
not a watch page
stopped

**Comment by wthueb** [comment]
The new like buttons: https://i.imgur.com/mQym8W9.png

**Comment by wthueb** [comment]
Actually, looking at the log, it could be a different issue. I was on a video when getting that log, however it's saying that I was at https://www.youtube.com/feed/subscriptions

**Comment by Taknok** [comment]
This is due to youtube new dynamic component (load an angular component without reloading the page). It is used for the small player in bottom right for example. We have to find the event and listen it (if possible, cause minifying etc)

**Comment by austencm** [comment]
I saw those new buttons too but they're back to the old ones for me now. Maybe they're doing A/B testing?

@wthueb do you remember if you were using the miniplayer at the time?

**Comment by wthueb** [comment]
Didn't mean to close the issue.

They have disappeared for me too, and no, I was not explicitly using the mini player at the time, but then again I think it's always "enabled" even if you don't use it.
