### ISSUE TITLE
Extension not work

### ISSUE THREAD

**Issue by UtkuGARIP** [austencm/youtube-auto-like#67]
Hello

I guess because of my Youtube new style, the likes extension is not working.

__________________________
### Log
Mon Mar 22 2021
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
YouTube variant: material
navigated: https://www.youtube.com/watch?v=ea7lVxPJ-10
loading options...
...options loaded (disabled: false,like_what: all,like_when: timed)
liker initialized
not a watch page
stopped

**Comment by FloridaStream** [comment]
for me too, today, now, dont work, is a recent problem for me.

**Comment by jjorstad2** [comment]
> for me too, today, now, dont work, is a recent problem for me.

I found a workaround set it to "All videos" instead of "Only videos from subscribed channels" it is working for me. Then on the videos I don't actually like I just change it or undo the like it did.

**Comment by austencm** [comment]
Sorry, youtube changed the sub button again! Fixed in the latest release: https://github.com/austencm/youtube-auto-like/releases/latest/download/release.zip
