### ISSUE TITLE
Problem with plugin (user not subscribed) on subscribed channel.

### ISSUE THREAD

**Issue by FloridaStream** [austencm/youtube-auto-like#68]
Problem with plugin on subscribed channel. dont detect channel subscribed. Only work selecting **All Videos**.
@austencm 

__________________________
### Log
Tue Apr 13 2021
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36
YouTube variant: material
navigated: https://www.youtube.com/
loading options...
...options loaded (disabled: false,like_what: subscribed,like_when: percent)
liker initialized
not a watch page
stopped
liker initialized
waiting for video...
...video ready
waiting for buttons...
...buttons ready
user not subscribed
stopped

**Comment by Taknok** [comment]
This is due to a new html version of Youtube, content did not change for the user, but the HTML has evolved.
@austencm here is my commit for grapping sub button on all 3 yt version currently ongoing #5ee6264

**Comment by FloridaStream** [comment]
@Taknok You can make a build? tks bro

**Comment by Taknok** [comment]
Busy now, this WE maybe. Sry

**Comment by austencm** [comment]
Working on this! I'll have a new release out later today.

**Comment by austencm** [comment]
https://github.com/austencm/youtube-auto-like/releases/latest/download/release.zip
