### ISSUE TITLE
Extension stopped working after updating chrome

### ISSUE THREAD

**Issue by M-Zuber** [austencm/youtube-auto-like#69]
I updated chrome, and then the extension stopped working (loaded from local copy due to not being in the store, no changes, newest version)

Additionally, got an error of `Uncaught (in promise) Error: Extension context invalidated.`, but that was on a channel page
Attached is a screenshot of all the context I have for that...
![image](https://user-images.githubusercontent.com/4746537/114586486-655f5380-9c8d-11eb-95e5-68a3fd9fe3e0.png)

__________________________
### Log
Tue Apr 13 2021
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36
YouTube variant: material
navigated: https://www.youtube.com/watch?v=UrwVSvmM8oU
loading options...
...options loaded (disabled: false,like_what: subscribed,like_when: instantly)
liker initialized
not a watch page
stopped
liker initialized
waiting for buttons...
...buttons ready
video already rated
stopped

**Comment by austencm** [comment]
Not sure what could be causing this issue, but try today's release and see if it helps? https://github.com/austencm/youtube-auto-like/releases/latest/download/release.zip

**Comment by FloridaStream** [comment]
Last version is working @M-Zuber 
Try reinstall. Delete current version from chrome and instal last version release.

**Comment by M-Zuber** [comment]
Thank you!!
