### ISSUE TITLE
Problem with sub only mode

### ISSUE THREAD

**Issue by NitramO-YT** [austencm/youtube-auto-like#70]
The like button is not pressed when i watched 50% of the video and even if i'm subscribed...

__________________________
### Log
Wed Apr 14 2021
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 OPR/73.0.3856.427
YouTube variant: material
navigated: https://www.youtube.com/watch?v=lR0Dj4ue6qs
loading options...
...options loaded (disabled: false,like_what: subscribed,like_when: percent)
liker initialized
waiting for video...
...video ready
waiting for buttons...
...buttons ready
user not subscribed
stopped

**Comment by Taknok** [comment]
Same as #68 , fix is underdevelopment :)

**Comment by austencm** [comment]
https://github.com/austencm/youtube-auto-like/releases/latest/download/release.zip
