### ISSUE TITLE
Problem with AutoLike

### ISSUE THREAD

**Issue by AtIasz** [austencm/youtube-auto-like#71]
I am subscribed to the linked channel, and I don't get to use the auto-like function. I've tried reinstalling it, got the latest version from GH but didn't work at all.

__________________________
### Log
Sat Apr 17 2021
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 OPR/73.0.3856.434
YouTube variant: material
navigated: https://www.youtube.com/watch?v=9wc6OpsEGGk
loading options...
...options loaded (disabled: false,like_what: subscribed,like_when: instantly)
liker initialized
waiting for buttons...
...buttons ready
user not subscribed
stopped
liker initialized
not a watch page
stopped
liker initialized
waiting for buttons...
...buttons ready
user not subscribed
stopped

**Comment by Taknok** [comment]
Thank you for the report. Logs indicates it is the same issue as #68 . Fix is ongoing :)

**Comment by austencm** [comment]
https://github.com/austencm/youtube-auto-like/releases/latest/download/release.zip
