### ISSUE TITLE
Issue on loading unpacked extension on OperaGX

### ISSUE THREAD

**Issue by NitramO-YT** [austencm/youtube-auto-like#73]
Hi, i tried to update my YouTybe-Auto-Like version by downloading the last version of unpacked extension zip and when i load it with OperaGX (which is pretty similar to Chrome and use Chromium, so it can run Chrome's extensions!) it give me these errors:

- **'action' requires nightly channel or newer, but this is the Stable channel.**
```
{"name":"__MSG_appName__","description":"__MSG_appDesc__","homepage_url":"https://github.com/austencm/youtube-auto-like","version":"2.6.0","manifest_version":3,"default_locale":"en","minimum_chrome_version":"88","incognito":"split","permissions":["storage","notifications"],"icons":{"128":"assets/images/128x128.png"},"action":{"default_icon":{"16":"assets/images/16x16.png","32":"assets/images/32x32.png","48":"assets/images/48x48.png"},"default_title":"__MSG_appName__","default_popup":"options.html"},"content_scripts":[{"matches":["*://youtube.com/*","*://*.youtube.com/*"],"js":["content.js"],"run_at":"document_end"}],"background":{"service_worker":"background.js"},"options_ui":{"page":"options.html"}}
```
_Inside this code above, this block is highlighted:_
```
"action":{"default_icon":{"16":"assets/images/16x16.png","32":"assets/images/32x32.png","48":"assets/images/48x48.png"},"default_title":"__MSG_appName__","default_popup":"options.html"}
```
- **'background.service_worker' requires developer channel or newer, but this is the Stable channel.**
```
Nothing to see here, go on your way.
```
- **The maximum currently-supported manifest version is 2, but this is 3. Certain features may not work as expected.**
```
{"name":"__MSG_appName__","description":"__MSG_appDesc__","homepage_url":"https://github.com/austencm/youtube-auto-like","version":"2.6.0","manifest_version":3,"default_locale":"en","minimum_chrome_version":"88","incognito":"split","permissions":["storage","notifications"],"icons":{"128":"assets/images/128x128.png"},"action":{"default_icon":{"16":"assets/images/16x16.png","32":"assets/images/32x32.png","48":"assets/images/48x48.png"},"default_title":"__MSG_appName__","default_popup":"options.html"},"content_scripts":[{"matches":["*://youtube.com/*","*://*.youtube.com/*"],"js":["content.js"],"run_at":"document_end"}],"background":{"service_worker":"background.js"},"options_ui":{"page":"options.html"}}
```
_Inside this code above, this block is highlighted:_
```
"manifest_version":3
```

__________________________
### Log
[no log found]

**Comment by austencm** [comment]
v2.6.0 uses manifest v3, a new version of the extension API. Based on the errors you’re getting it looks like OperaGX hasn’t updated to the new version yet. I’ll see if there’s a way I can include backward compatibility or maybe just patch the previous release.

**Comment by austencm** [comment]
@NitramO-YT made a version of v2.5.2 with the subscribe button patched! Let me know if you have any issues with that. https://github.com/austencm/youtube-auto-like/releases/download/v2.5.2/v2.5.2-patched.zip

I suggest trying the latest version again in a couple months. OperaGX will probably support v3 by then.

**Comment by NitramO-YT** [comment]
> @NitramO-YT made a version of v2.5.2 with the subscribe button patched! Let me know if you have any issues with that. https://github.com/austencm/youtube-auto-like/releases/download/v2.5.2/v2.5.2-patched.zip
> 
> I suggest trying the latest version again in a couple months. OperaGX will probably support v3 by then.

Thank you! I'll try it and i think i'm gonna report this issue too on the OperaGX forums!

**Comment by NitramO-YT** [comment]
This is working, thx!
