### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by PhilipDukhov** [austencm/youtube-auto-like#74]
I was trying to build the project. First I've faced was
`sh: xt-clean: command not found`

I have found some outdated package that looks like what I need: `pm-extension-cli`

Then  I encountered more understandable errors:
`Error: Cannot find module 'expand-range'`
`Error: Cannot find module 'preserve'`

But after installing this two modules I've got an error:
`TypeError: isPlainObject is not a function`

Could you add build instructions?

**Comment by austencm** [comment]
Did you run `npm install` first?

**Comment by PhilipDukhov** [comment]
I had run npm install. 

Looks like the problem was in old caches, after I reset the folder it build fine, by bad.
