### ISSUE TITLE
Probable issue on patched version v2.5.2 in playlists/watch lists

### ISSUE THREAD

**Issue by NitramO-YT** [austencm/youtube-auto-like#75]
The patched version v2.5.2 seem to not working in a playlist/watch list because i watched more of 50% of the video and it didn't liked it!

> @NitramO-YT made a version of v2.5.2 with the subscribe button patched! Let me know if you have any issues with that. https://github.com/austencm/youtube-auto-like/releases/download/v2.5.2/v2.5.2-patched.zip
> 
> I suggest trying the latest version again in a couple months. OperaGX will probably support v3 by then.

_Originally posted by @austencm in https://github.com/austencm/youtube-auto-like/issues/73#issuecomment-822071012_

__________________________
### Log
Wed Apr 21 2021
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 OPR/73.0.3856.434
YouTube variant: material
navigated: https://www.youtube.com/watch?v=EFwNlHvzz5I&list=TLPQMjEwNDIwMjG_rurt-7YS3Q&index=2
loading options...
...options loaded (disabled: false,like_what: subscribed,like_when: percent)
liker initialized
not a watch page
stopped
liker initialized
waiting for video...
...video ready
waiting for buttons...
...buttons ready
like button clicked
stopped

**Comment by austencm** [comment]
Thanks for the heads up, I'll take a look.

**Comment by GeorgyBuns** [comment]
Same. Doesn’t work for me.

**Comment by markygnlg** [comment]
4 things you might want to test/try:
'
- there is now a v2.7.1 which was released about 24hrs ago as of this writing:
https://github.com/austencm/youtube-auto-like/releases
'
- secondly, I too found it 'not working' (with the 50% setting) but if I pressed 'F5'/refresh or opened the video in another tab (same as refreshing the page) the like button would be lit up: ie. it works but the graphics of the thumb only displays if you press refresh (I'm using v2.7.1 on Opera)
'
- try testing with 'Instantly'
'
- updates default to "Only videos from subbed channels" - it's working for me on all videos after I changed the setting to "ALL videos"
