### ISSUE TITLE
The patched version v2.5.2 is not working anymore!

### ISSUE THREAD

**Issue by NitramO-YT** [austencm/youtube-auto-like#77]
The patched version v2.5.2 is not working anymore, i watched more of 50% of the video and it didn't liked it!

> @NitramO-YT made a version of v2.5.2 with the subscribe button patched! Let me know if you have any issues with that. https://github.com/austencm/youtube-auto-like/releases/download/v2.5.2/v2.5.2-patched.zip
> 
> I suggest trying the latest version again in a couple months. OperaGX will probably support v3 by then.

_Originally posted by @austencm in https://github.com/austencm/youtube-auto-like/issues/73#issuecomment-822071012_

__________________________
### Log
Sat May 01 2021
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 OPR/73.0.3856.438
YouTube variant: material
navigated: https://www.youtube.com/watch?v=6F-6J8lXC4w
loading options...
...options loaded (disabled: false,like_what: subscribed,like_when: percent)
liker initialized
not a watch page
stopped
liker initialized
not a watch page
stopped
liker initialized
not a watch page
stopped
liker initialized
not a watch page
stopped

**Comment by GeorgyBuns** [comment]
Same. It doesn’t work for me either.

**Comment by markygnlg** [comment]
v2.6.0	Apr 17, 2021...

Feb 2021: Sadly, Chrome removed this extension for violating YouTube's terms of service (specifically the part about causing inaccurate measurements of user engagement). You can still load the extension locally by following these steps. Only do this for extensions you trust.

Download the latest release: https://github.com/austencm/youtube-auto-like/releases/latest/download/release.zip
Unzip release.zip and put it somewhere it won't get deleted accidentally
Open your extensions page in Chrome (in the top right, click the 3 dots > More Tools > Extensions)
Turn on Developer Mode (in the top right)
Click 'Load unpacked' and select the unzipped release folder
Extensions loaded this way are unable to update automatically. Keep an eye out for a badge on the icon that indicates a new version is available.

**Comment by GeorgyBuns** [comment]
@markygnlg thanks for the reply. That was my guess that Google did something on their side so you were unable to publish the extension on their store.

**Comment by markygnlg** [comment]
No probs. FYI, its not my extension. I came here (via the link in the extensions option page) to find a fix too, the info I posted above came from the main page - click on "<> code" on the top right of the page (to the left of the "Issues" link).

**Comment by GeorgyBuns** [comment]
@markygnlg oh, I see. Well, anyway, thanks for the info!

**Comment by NitramO-YT** [comment]
@austencm I'm sorry to inform you that if you don't update your extension I would be forced to use a different one, I'm already patient enough using an extension that isn't even on the Chrome Web Store anymore!

**Comment by Taknok** [comment]
They is another youtube auto like available on store ?

**Comment by NitramO-YT** [comment]
> They is another youtube auto like available on store ?

I think so, otherwise i can make my own one :)

**Comment by NitramO-YT** [comment]
> @NitramO-YT I've been pretty busy lately with my actual job. If you can find an alternative extension that supports OperaGX I say go for it. Since I'm unfamiliar with OperaGX, this is going to be a more difficult issue to debug.

I'm sorry to hear it, so i think i'll find an alternative extension for OperaGX, thank you anyway for tried to provide a special version for OperaGX even if it didn't last long :/ Good luck for the continuation!

**Comment by markygnlg** [comment]
version 2.6.0 works for me, except the autolike after 50% - both instant & after 2 minutes options work.

**Comment by markygnlg** [comment]
Opera v76.0.4017.107 with "Install Chrome Extensions" v2.5.9

**Comment by markygnlg** [comment]
I'll also add that "Save as MHTML" Version 0.1.0 by brian-girko for Opera did not work but the same version for Chrome did - by using "Install Chrome Extensions" (the Chrome version is now 0.2.2 & still works so I have not tested if there is a newer Opera version).

I do not know if that's any help but I thought I would mention that an Opera specific extension failed where a Chrome extension worked on Opera.
