### ISSUE TITLE
Option "After watching 50%" does not seem to work on v2.6.0 (1st 2 options do work)

### ISSUE THREAD

**Issue by markygnlg** [austencm/youtube-auto-like#78]
I've found that the other 2 options, instantly & after 2 minutes, work but not the 3rd option of After watching 50%.
Thanks for the 2.6.0 update, I didn't realise there was an issue with youtube.

__________________________
### Log
Sat May 08 2021
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.128 Safari/537.36 OPR/75.0.3969.243
navigated: https://www.youtube.com/watch?v=UTY5Q-dX6mg&feature=emb_imp_woyt
loading options...
...options loaded (disabled: false,like_what: all,like_when: timed)
liker initialized
liker started
waiting for video...

**Comment by austencm** [comment]
Hey @markygnlg, I've been trying to reproduce this but so far no luck. Can you confirm it still isn't working on your end?

**Comment by markygnlg** [comment]
I've just changed the option - I'll let you know after a few days.

I'll add that there were 2 ways I tested this: 1st was to leave it on 50% after the v2.6.0 update but when I noticed that playlists that I've watched had no thumbs up I then clicked the scroll-bar below the video before & after the 50% mark (both on short & long videos).
When the above 2 tests failed I changed the option to 'immediately' & later to 'after 2 minutes' where both always worked - either by manually clicking on the scroll-bar below the video or by letting the video play on its own; it worked both ways, even on videos shorter than 2 minutes.

**Comment by markygnlg** [comment]
All's good it seems!

I gave it a quick test on a video of length 39:30 but the 1st test auto-liked at 17 minutes. I've tested it a few times with & without cinema mode (the 1st test was without cinema mode) & all is well it seems - auto-likes @17:45 repeatedly now.

I do not know why playlists were not auto-liking previously - i tried changing options, disabling re-enabling the extension & different combinations of options but now it's working...

Thanks for making me retest it as many videos I do not like I close after the 2 minute mark. The 50% option is something I'd always preferred.

**Comment by markygnlg** [comment]
A bit more info for clarity:

I manually downloaded v2.6.0 while I discovered 2 tv shows available on youtube that I enjoyed so I found 'their' playlists & watched via those playlists.

I did not realise that other 'youtubers/channels' had re-posted those episodes, so when I re-watched some episodes I was actually watching episodes from re-posting/re-uploading youtube channels where there was no 'like' shown... 

ie. the '50% auto-like' may have been working always but due to re-uploading I was re-watching episodes that I technically had never seen!!
