### ISSUE TITLE
with every settings the add-on never works

### ISSUE THREAD

**Issue by RossettiDiego03** [austencm/youtube-auto-like#79]
__________________________
### Log
Sun May 09 2021
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.128 Safari/537.36 OPR/75.0.3969.259
YouTube variant: material
navigated: https://www.youtube.com/watch?v=5dFMSzF30KI&t=73s&ab_channel=QueiDueSulServer2
loading options...
...options loaded (disabled: false,like_what: subscribed,like_when: instantly)
liker initialized
not a watch page
stopped
liker initialized
not a watch page
stopped

**Comment by markygnlg** [comment]
4 things you might want to test/try:
'
- there is now a v2.7.1 which was released about 24hrs ago as of this writing:
https://github.com/austencm/youtube-auto-like/releases
'
- secondly, I too found it 'not working' (with the 50% setting) but if I pressed 'F5'/refresh or opened the video in another tab (same as refreshing the page) the like button would be lit up: ie. it works but the graphics of the thumb only displays if you press refresh (I'm using v2.7.1 on Opera)
'
- try testing with 'Instantly'
'
- updates default to "Only videos from subbed channels" - it's working for me on all videos after I changed the setting to "ALL videos"
