### ISSUE TITLE
Not work on MS Edge

### ISSUE THREAD

**Issue by tonyjeffferson** [austencm/youtube-auto-like#83]
From version 2.7.0 not working on MS Edge

**Comment by austencm** [comment]
Hmm never tested on Edge before but nice to know it's worked there until now. Probably an issue with manifest v3. Not easy for me to test on Edge though. Do you see any errors when you load the extension? Or does the liking just not work?

**Comment by tonyjeffferson** [comment]
The liking just not work

**Comment by luca1197** [comment]
The extension (version 2.7.1) works fine for me on Edge 91.0.864.37.
Maybe try updating your browser, reinstall the extension and check the extension settings?

**Comment by tonyjeffferson** [comment]
The extension settings is ok. I use Edge canary 92.0.901.0

**Comment by tonyjeffferson** [comment]
> The extension (version 2.7.1) works fine for me on Edge 91.0.864.37.
> Maybe try updating your browser, reinstall the extension and check the extension settings?

I installed the latest public release of MS Edge (91.0.864.37), and the extension continues not working for me

**Comment by tonyjeffferson** [comment]
The problem isn't with your extension. Microsoft is working on something that break this. I updated my browser today and the version 1.6.0 has stoped too
