### ISSUE TITLE
New Youtube layout breaks extension

### ISSUE THREAD

**Issue by kopach** [austencm/youtube-auto-like#88]
It seems like YouTube has introduced new styling/layout of Like button. The extension doesn't work anymore with this new layout.

**Comment by austencm** [comment]
Lately it appears youtube has been testing new button styles. Right now they look same for me and the extension is working fine on my end but I've seen different ones too in the past. A couple other people reported this also, so you're not alone. Unfortunately I can't do anything much about it unless they change the buttons for everybody. BUT, if you can save a page where you're seeing the new buttons (cmd+S on a mac or right click -> save as) and send that file to me at heyausten@gmail.com I might be able to put in a patch for it.

**Comment by Taknok** [comment]
Here is what I have done for the firefox version, maybe it can help you.
https://github.com/Taknok/youtube-auto-like/commit/e5af5a75554ad13e94cd49ced8a2e3b26046a09b

While fixing the issue I see that the HTML code is present for everyone but css attribute `hidden` is set by JS (JS check region cookies and activate or not the new layout). Youtube client version I tested is 2.20210713.07.00 (you can be checked with `window.ytcfg.get("INNERTUBE_CLIENT_VERSION")`). If you search the selector `document.querySelectorAll("#actions #top-level-buttons-computed.top-level-buttons.style-scope.ytd-menu-renderer")` you should get it even if hidden.

It is also working on wayback machine : http://web.archive.org/web/20210714055445if_/https://www.youtube.com/watch?v=dQw4w9WgXcQ
![image](https://user-images.githubusercontent.com/12498020/125762736-96f396f8-4f56-4751-be27-d2a28bb5a294.png)

**Comment by austencm** [comment]
You trying to rickroll me @Taknok? I can see link previews in gmail 😒

Joking aside, that's some good detective work. Thanks for the tip.

**Comment by Outwise** [comment]
Looks like this got resolved, it was working for a lovely while! But Youtube changed the icon a few weeks ago and... of course, it broke the liker again. 

Youtuuube! ✊😠

**Comment by Taknok** [comment]
https://github.com/Taknok/youtube-auto-like/issues/50

From "Fix new yt layout" https://github.com/Taknok/youtube-auto-like/commits/master

Playlist also changed, and I did not saw that, thus there is another commit after, meaning "Fixing playlist" may interest you.
