### ISSUE TITLE
Youtube Auto Like Extension Not Working for 3 Days

### ISSUE THREAD

**Issue by UtkuGARIP** [austencm/youtube-auto-like#98]
Hi

Youtube Auto Like extension stopped working after Youtube update. The update is not as important as it seems, when you hover over the video with the mouse cursor, the video is played a little larger. Involuntarily with subtitles on and sound off. Oh what a great feature(!)

Anyway, I hope you can fix the problem caused by this stupid update.
I wish you a good day and work.

__________________________
### Log
YouTube Auto Like v2.7.1
Sun Jan 16 2022
User agent: 
{
  "browser": {
    "name": "Chrome",
    "version": "97.0.4692.71"
  },
  "os": {
    "name": "Windows",
    "version": "NT 6.1",
    "versionName": "7"
  },
  "platform": {
    "type": "desktop"
  },
  "engine": {
    "name": "Blink"
  }
}
navigated: https://www.youtube.com/
loading options...
...options loaded ({
  "disabled": false,
  "like_what": "all",
  "like_when": "timed",
  "like_when_minutes": "1",
  "like_when_percent": "50"
})
liker started
waiting for video...

**Comment by wthueb** [comment]
Are you clicking to open the video? Is the address bar in Chrome changing? If so, the log appears to be incomplete.

**Comment by UtkuGARIP** [comment]
Are you opening the video? Are you serious? Come on man, of course I do. My browser is Brave browser using Chrome infrastructure, this cannot be a problem because when I started using the Brave browser, I first entered Youtube and watched the video and liked it automatically. But after the update it started to not like. :(

**Comment by wthueb** [comment]
I don't mean to sound demeaning, however the first thing the content script does is logs the URL the script is running on. Your log shows `navigated: https://www.youtube.com/` as the last log message, notably without the standard `/watch?v=VIDEOID`. Unless YouTube has made a *drastic* change (which I don't believe it has, as I am also getting the hovering video autoplay thing), the log is incomplete.

**Comment by wthueb** [comment]
Ah, I just realized that you probably used the report an error button in the extension. You'll have to do it from a video page instead of from the YouTube homepage.

However, I assume this is related to #95. If you could share the HTML of the video page by saving the page (Ctrl+S) and attaching it here, that would make it simple to verify.

**Comment by UtkuGARIP** [comment]
The 1st picture is Youtube update, the 2nd picture shows that I opened the video and after 1 minute the video likes did not work. Sorry I couldn't answer while preparing the pictures.
![1](https://user-images.githubusercontent.com/12918033/149673236-70b883aa-77c8-4936-bcdb-5eb59e4552dc.png)
![2](https://user-images.githubusercontent.com/12918033/149673244-94ed1f63-3d8d-44ec-897e-e6b4d82cfe76.png)

**Comment by wthueb** [comment]
Unfortunately it is quite difficult to determine what the issue is without access to the HTML of the page. Screenshots do not suffice. If you could save the contents of the page (Ctrl+S) and share them, that would be the simplest way to fix this issue.

**Comment by UtkuGARIP** [comment]
I'm sorry for the delay. I can't attach the HTML file, I get the not supported file warning.

**Comment by wthueb** [comment]
Ah, strange how GitHub only allows certain file extensions. Feel free to email the HTML file to me at wilhueb@gmail.com and I can take a look at it.

**Comment by wthueb** [comment]
Upon inspecting the HTML file you provided, the selector in v2.7.1 seems to be correct:

![image](https://user-images.githubusercontent.com/23162665/149677601-18c5e569-9d84-4d3e-bc48-188d8ad53cfd.png)

I'm not quite sure what could be causing this discrepancy. Once again, I have the new YouTube update with the hover autoplay feature (`window.ytcfg.get("INNERTUBE_CLIENT_VERSION") = '2.20220114.01.00'`—if that is the proper indicator—which matches the HTML document you have provided) and the extension works fine. Hopefully someone will come along with a better idea of what the issue could be.

**Comment by UtkuGARIP** [comment]
Sorry, I have no technical knowledge. :( I just wanted to inform. I hope this Youtube block is also overcome.
----------------
The extension works sometimes. That's enough for me.

**Comment by austencm** [comment]
Interesting, youtube isn't giving me this feature yet. I'll look into it for the next version, coming soon™

**Comment by UtkuGARIP** [comment]
The extension debugging thing has decided to work. :)
![1](https://user-images.githubusercontent.com/12918033/150169994-828036c8-c582-4a18-b504-98d65ea154af.png)
![2](https://user-images.githubusercontent.com/12918033/150170001-8b43167b-eb02-440b-baa7-1c2f86119ef9.png)
Yellow text: 1
(()=>{var e={190:()=>{async function e(){const e=chrome.runtime.getManifest().version,t=await fetch("https://api.github.com/repos/austencm/youtube-auto-like/releases/latest"),r=await t.json(),o=r.tag_name.replace("v","");e!==o?(chrome.action.setBadgeText({text:"1"}),chrome.storage.local.set({latestRelease:{version:o,downloadUrl:r.assets[0].browser_download_url}})):(chrome.action.setBadgeText({text:""}),chrome.storage.local.remove("latestRelease"))}chrome.runtime.onStartup.addListener(e),chrome.runtime.onInstalled.addListener(e)}},t={};function r(o){var a=t[o];if(void 0!==a)return a.exports;var s=t[o]={exports:{}};return e[o](s,s.exports,r),s.exports}r.n=e=>{var t=e&&e.__esModule?()=>e.default:()=>e;return r.d(t,{a:t}),t},r.d=(e,t)=>{for(var o in t)r.o(t,o)&&!r.o(e,o)&&Object.defineProperty(e,o,{enumerable:!0,get:t[o]})},r.o=(e,t)=>Object.prototype.hasOwnProperty.call(e,t),(()=>{"use strict";r(190)})()})();

**Comment by Apocyl** [comment]
Mine has been partially working and partially not working. It also appears to me that sometimes, for no reason at all, the video pauses JUST before it would automatically like the video but i wasn't able to replicate this.

**Comment by austencm** [comment]
Sorry about the wait! Please update to v2.7.3 and let me know if you're still having issues.

@UtkuGARIP the error in your last screenshot is from the service worker, which just checks for updates. It shouldn't interfere with the actual liking part of the extension but it does look like it failed for some reason, possibly a network issue. Please let me know if you see that frequently 🙏🏻
